In [ ]:
import pandas as pd 
import numpy as np
df_row = pd.read_csv("ElectricCarData_Clean.csv") #load data 
df=df_row.copy() #Its important to copy the data 
print(df)

           Brand                            Model  AccelSec  TopSpeed_KmH  \
0         Tesla     Model 3 Long Range Dual Motor       4.6           233
1    Volkswagen                         ID.3 Pure      10.0           160
2      Polestar                                 2       4.7           210
3           BMW                              iX3        6.8           180
4         Honda                                e        9.5           145
..           ...                              ...       ...           ...
98       Nissan                       Ariya 63kWh       7.5           160
99         Audi     e-tron S Sportback 55 quattro       4.5           210
100      Nissan               Ariya e-4ORCE 63kWh       5.9           200
101      Nissan   Ariya e-4ORCE 87kWh Performance       5.1           200
102       Byton                 M-Byte 95 kWh 2WD       7.5           190

     Range_Km  Efficiency_WhKm FastCharge_KmH RapidCharge PowerTrain  \
0         450              161            940         Yes        AWD
1         270              167            250         Yes        RWD
2         400              181            620         Yes        AWD
3         360              206            560         Yes        RWD
4         170              168            190         Yes        RWD
..        ...              ...            ...         ...        ...
98        330              191            440         Yes        FWD
99        335              258            540         Yes        AWD
100       325              194            440         Yes        AWD
101       375              232            450         Yes        AWD
102       400              238            480         Yes        AWD

       PlugType  BodyStyle Segment  Seats  PriceEuro
0    Type 2 CCS      Sedan       D      5      55480
1    Type 2 CCS  Hatchback       C      5      30000
2    Type 2 CCS   Liftback       D      5      56440
3    Type 2 CCS        SUV       D      5      68040
4    Type 2 CCS  Hatchback       B      4      32997
..          ...        ...     ...    ...        ...
98   Type 2 CCS  Hatchback       C      5      45000
99   Type 2 CCS        SUV       E      5      96050
100  Type 2 CCS  Hatchback       C      5      50000
101  Type 2 CCS  Hatchback       C      5      65000
102  Type 2 CCS        SUV       E      5      62000

[103 rows x 14 columns]

In [4]:
df.head()

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
1,Volkswagen,ID.3 Pure,10.0,160,270,167,250,Yes,RWD,Type 2 CCS,Hatchback,C,5,30000
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
3,BMW,iX3,6.8,180,360,206,560,Yes,RWD,Type 2 CCS,SUV,D,5,68040
4,Honda,e,9.5,145,170,168,190,Yes,RWD,Type 2 CCS,Hatchback,B,4,32997

In [5]:
df.info

<bound method DataFrame.info of            Brand                            Model  AccelSec  TopSpeed_KmH  \
0         Tesla     Model 3 Long Range Dual Motor       4.6           233
1    Volkswagen                         ID.3 Pure      10.0           160
2      Polestar                                 2       4.7           210
3           BMW                              iX3        6.8           180
4         Honda                                e        9.5           145
..           ...                              ...       ...           ...
98       Nissan                       Ariya 63kWh       7.5           160
99         Audi     e-tron S Sportback 55 quattro       4.5           210
100      Nissan               Ariya e-4ORCE 63kWh       5.9           200
101      Nissan   Ariya e-4ORCE 87kWh Performance       5.1           200
102       Byton                 M-Byte 95 kWh 2WD       7.5           190

     Range_Km  Efficiency_WhKm FastCharge_KmH RapidCharge PowerTrain  \
0         450              161            940         Yes        AWD
1         270              167            250         Yes        RWD
2         400              181            620         Yes        AWD
3         360              206            560         Yes        RWD
4         170              168            190         Yes        RWD
..        ...              ...            ...         ...        ...
98        330              191            440         Yes        FWD
99        335              258            540         Yes        AWD
100       325              194            440         Yes        AWD
101       375              232            450         Yes        AWD
102       400              238            480         Yes        AWD

       PlugType  BodyStyle Segment  Seats  PriceEuro
0    Type 2 CCS      Sedan       D      5      55480
1    Type 2 CCS  Hatchback       C      5      30000
2    Type 2 CCS   Liftback       D      5      56440
3    Type 2 CCS        SUV       D      5      68040
4    Type 2 CCS  Hatchback       B      4      32997
..          ...        ...     ...    ...        ...
98   Type 2 CCS  Hatchback       C      5      45000
99   Type 2 CCS        SUV       E      5      96050
100  Type 2 CCS  Hatchback       C      5      50000
101  Type 2 CCS  Hatchback       C      5      65000
102  Type 2 CCS        SUV       E      5      62000

[103 rows x 14 columns]>

In [ ]:
df.shape #It give u shape how many row and column are presnt in data

(103, 14)

In [ ]:
df.columns  #It give u name of all columns

Index(['Brand', 'Model', 'AccelSec', 'TopSpeed_KmH', 'Range_Km',
       'Efficiency_WhKm', 'FastCharge_KmH', 'RapidCharge', 'PowerTrain',
       'PlugType', 'BodyStyle', 'Segment', 'Seats', 'PriceEuro'],
      dtype='str')

In [ ]:
df.describe()  #TO calulate the data .

,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,Seats,PriceEuro
count,103.000000,103.000000,103.000000,103.000000,103.000000,103.000000
mean,7.396117,179.194175,338.786408,189.165049,4.883495,55811.563107
std,3.017430,43.573030,126.014444,29.566839,0.795834,34134.665280
min,2.100000,123.000000,95.000000,104.000000,2.000000,20129.000000
25%,5.100000,150.000000,250.000000,168.000000,5.000000,34429.500000
50%,7.300000,160.000000,340.000000,180.000000,5.000000,45000.000000
75%,9.000000,200.000000,400.000000,203.000000,5.000000,65000.000000
max,22.400000,410.000000,970.000000,273.000000,7.000000,215000.000000

In [ ]:
df.isnull().sum() #To check there is any null value

Brand              0
Model              0
AccelSec           0
TopSpeed_KmH       0
Range_Km           0
Efficiency_WhKm    0
FastCharge_KmH     0
RapidCharge        0
PowerTrain         0
PlugType           0
BodyStyle          0
Segment            0
Seats              0
PriceEuro          0
dtype: int64

In [10]:
df["Brand"]

0           Tesla
1      Volkswagen
2        Polestar
3             BMW
4           Honda
          ...
98         Nissan
99           Audi
100        Nissan
101        Nissan
102         Byton
Name: Brand, Length: 103, dtype: str

In [11]:
df[df["TopSpeed_KmH"]>190]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
0,Tesla,Model 3 Long Range Dual Motor,4.6,233,450,161,940,Yes,AWD,Type 2 CCS,Sedan,D,5,55480
2,Polestar,2,4.7,210,400,181,620,Yes,AWD,Type 2 CCS,Liftback,D,5,56440
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000
8,Tesla,Model 3 Standard Range Plus,5.6,225,310,153,650,Yes,RWD,Type 2 CCS,Sedan,D,5,46380
13,BMW,i4,4.0,200,450,178,650,Yes,RWD,Type 2 CCS,Sedan,D,5,65000
16,Porsche,Taycan Turbo S,2.8,260,375,223,780,Yes,AWD,Type 2 CCS,Sedan,F,4,180781
21,Tesla,Model Y Long Range Dual Motor,5.1,217,425,171,930,Yes,AWD,Type 2 CCS,SUV,D,7,58620
23,Audi,e-tron GT,3.5,240,425,197,850,Yes,AWD,Type 2 CCS,Sedan,F,4,125000
24,Tesla,Model 3 Long Range Performance,3.4,261,435,167,910,Yes,AWD,Type 2 CCS,Sedan,D,5,61480
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
39,Mercedes,EQA,5.0,200,350,171,440,Yes,AWD,Type 2 CCS,SUV,C,5,45000
40,Tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990
42,Audi,e-tron Sportback 55 quattro,5.7,200,380,228,610,Yes,AWD,Type 2 CCS,SUV,E,5,81639
47,Porsche,Taycan 4S,4.0,250,365,195,730,Yes,AWD,Type 2 CCS,Sedan,F,4,102945
50,Audi,e-tron 55 quattro,5.7,200,365,237,590,Yes,AWD,Type 2 CCS,SUV,E,5,79445
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000
54,Tesla,Model X Long Range,4.6,250,450,211,490,Yes,AWD,Type 2,SUV,F,7,85990
59,Tesla,Model S Performance,2.5,261,505,188,550,Yes,AWD,Type 2,Liftback,F,5,96990
61,Tesla,Model Y Long Range Performance,3.7,241,410,177,900,Yes,AWD,Type 2 CCS,SUV,D,7,65620
63,Jaguar,I-Pace,4.8,200,365,232,340,Yes,AWD,Type 2 CCS,SUV,E,5,75351
65,Porsche,Taycan 4S Plus,4.0,250,425,197,890,Yes,AWD,Type 2 CCS,Sedan,F,4,109302
72,Porsche,Taycan Cross Turismo,3.5,250,385,217,770,Yes,AWD,Type 2 CCS,Station,F,4,150000
79,Porsche,Taycan Turbo,3.2,260,390,215,810,Yes,AWD,Type 2 CCS,Sedan,F,4,148301
81,Tesla,Model X Performance,2.8,250,440,216,480,Yes,AWD,Type 2,SUV,F,7,102990
90,Audi,e-tron S 55 quattro,4.5,210,320,270,510,Yes,AWD,Type 2 CCS,SUV,E,5,93800
93,Nissan,Ariya e-4ORCE 87kWh,5.7,200,420,207,500,Yes,AWD,Type 2 CCS,Hatchback,C,5,57500
99,Audi,e-tron S Sportback 55 quattro,4.5,210,335,258,540,Yes,AWD,Type 2 CCS,SUV,E,5,96050
100,Nissan,Ariya e-4ORCE 63kWh,5.9,200,325,194,440,Yes,AWD,Type 2 CCS,Hatchback,C,5,50000
101,Nissan,Ariya e-4ORCE 87kWh Performance,5.1,200,375,232,450,Yes,AWD,Type 2 CCS,Hatchback,C,5,65000

In [12]:
df[df["TopSpeed_KmH"]>400]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [13]:
df[df["Range_Km"]>800]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [14]:
df[df["Range_Km"]>600]

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [15]:
df.sort_values("Range_Km")

,Brand,Model,AccelSec,TopSpeed_KmH,Range_Km,Efficiency_WhKm,FastCharge_KmH,RapidCharge,PowerTrain,PlugType,BodyStyle,Segment,Seats,PriceEuro
91,Smart,EQ fortwo cabrio,11.9,130,95,176,-,No,RWD,Type 2,Cabrio,A,2,24565
77,Smart,EQ forfour,12.7,130,95,176,-,No,RWD,Type 2,Hatchback,A,4,22030
82,Smart,EQ fortwo coupe,11.6,130,100,167,-,No,RWD,Type 2,Hatchback,A,2,21387
57,Renault,Twingo ZE,12.6,135,130,164,-,No,RWD,Type 2,Hatchback,A,4,24790
68,Renault,Kangoo Maxi ZE 33,22.4,130,160,194,-,No,FWD,Type 2,SPV,N,5,38000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40,Tesla,Model S Long Range,3.8,250,515,184,560,Yes,AWD,Type 2,Liftback,F,5,79990
48,Lightyear,One,10.0,150,575,104,540,Yes,AWD,Type 2 CCS,Liftback,F,5,149000
5,Lucid,Air,2.8,250,610,180,620,Yes,AWD,Type 2 CCS,Sedan,F,5,105000
33,Tesla,Cybertruck Tri Motor,3.0,210,750,267,710,Yes,AWD,Type 2 CCS,Pickup,N,6,75000
51,Tesla,Roadster,2.1,410,970,206,920,Yes,AWD,Type 2 CCS,Cabrio,S,4,215000

In [16]:
df.groupby("Range_Km").mean(numeric_only=True)

           AccelSec  TopSpeed_KmH  Efficiency_WhKm     Seats      PriceEuro
Range_Km
95        12.300000    130.000000       176.000000  3.000000   23297.500000
100       11.600000    130.000000       167.000000  2.000000   21387.000000
130       12.600000    135.000000       164.000000  4.000000   24790.000000
160       22.400000    130.000000       194.000000  5.000000   38000.000000
170        8.900000    145.000000       168.000000  4.000000   34459.000000
180        9.000000    150.000000       178.000000  5.000000   32646.000000
185        7.300000    150.000000       156.000000  4.000000   31681.000000
190       11.800000    136.500000       184.000000  6.000000   32573.000000
195       12.166667    130.000000       166.000000  4.000000   22028.000000
220        8.050000    142.000000       178.500000  5.000000   29617.000000
225        9.000000    140.000000       156.000000  5.000000   25500.000000
230        8.400000    158.500000       167.500000  4.500000   37329.500000
235        8.550000    152.500000       164.000000  4.500000   36208.500000
250        9.100000    152.500000       171.500000  4.666667   36507.000000
255        9.933333    146.666667       163.666667  5.000000   32735.000000
270        8.750000    160.000000       180.000000  5.000000   40000.000000
275        8.100000    150.000000       164.000000  5.000000   29414.000000
280        6.800000    190.000000       231.000000  5.000000   67358.000000
290       10.000000    160.000000       179.000000  5.000000   35000.000000
295        6.800000    190.000000       219.000000  5.000000   69551.000000
310        7.550000    182.500000       160.500000  5.000000   39756.500000
315       11.400000    135.000000       165.000000  5.000000   31184.000000
320        6.750000    185.000000       225.500000  5.000000   65650.000000
325        6.900000    182.333333       196.000000  5.000000   46912.333333
330        8.750000    150.000000       232.000000  6.000000   57815.500000
335        6.933333    170.000000       206.333333  5.000000   58004.333333
340        6.866667    166.666667       182.666667  5.000000   42854.000000
350        7.000000    180.000000       168.500000  5.000000   39000.000000
360        6.700000    180.000000       200.000000  5.000000   57470.000000
365        6.060000    196.800000       202.800000  4.800000   66283.000000
370        6.450000    173.500000       194.500000  5.000000   53794.500000
375        4.266667    213.333333       218.333333  4.666667  102072.666667
380        5.700000    200.000000       228.000000  5.000000   81639.000000
385        3.500000    250.000000       217.000000  4.000000  150000.000000
390        5.233333    210.000000       238.333333  5.000000   85767.000000
400        6.600000    181.166667       193.000000  5.000000   51122.500000
410        5.000000    210.500000       182.500000  6.000000   61560.000000
420        7.333333    173.333333       191.000000  5.000000   47500.000000
425        4.775000    216.750000       186.500000  4.750000   84480.500000
430        6.000000    180.000000       209.000000  5.000000   62900.000000
435        3.400000    261.000000       167.000000  5.000000   61480.000000
440        6.100000    190.000000       196.333333  5.333333   64642.000000
450        5.050000    215.750000       187.500000  5.500000   65236.250000
460        5.000000    190.000000       261.000000  6.000000   55000.000000
505        2.500000    261.000000       188.000000  5.000000   96990.000000
515        3.800000    250.000000       184.000000  5.000000   79990.000000
575       10.000000    150.000000       104.000000  5.000000  149000.000000
610        2.800000    250.000000       180.000000  5.000000  105000.000000
750        3.000000    210.000000       267.000000  6.000000   75000.000000
970        2.100000    410.000000       206.000000  4.000000  215000.000000